name: WooEconomy
version: '${project.version}'
main: de.alphaomegait.wooeconomy.wooeconomy.WooEconomy
api-version: '1.20'

softdepend: [ShopGUIPlus, Vault, PlaceholderAPI]

loadBefore:
  - WooOneblock
  - WooJobs
  - WooWorkbench
  - WooShop
  - WooVote
  - AOGens